-- Start of DDL Script for Package API_SIF_MOBILE.MB_INTERFACE_PKG
-- Generated 18-Feb-21 08:50:40 from API_SIF_MOBILE@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.18.1.199)(PORT = 1528)))(CONNECT_DATA =(SERVICE_NAME = afb12c)))

CREATE OR REPLACE 
PACKAGE api_sif_mobile.mb_interface_pkg
IS

    OK                            CONSTANT NUMBER := 0;
    NOK                           CONSTANT NUMBER := -1;
    ERROR                         CONSTANT NUMBER := -2;

    -- FONCTIONS EXTERNES
    PROCEDURE GETCARDSLIST (
            V_REQUEST    IN OUT NOCOPY CARDSLISTRQ,
            V_RESPONSE   IN OUT NOCOPY CARDSLISTRS);

    PROCEDURE GETACCOUNTSLIST (
        V_REQUEST    IN OUT NOCOPY ACCOUNTSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY ACCOUNTSLISTRS);

    PROCEDURE GETTRANSACTIONSLIST (
            V_REQUEST    IN OUT NOCOPY TRANSACTIONSLISTRQ,
            V_RESPONSE   IN OUT NOCOPY TRANSACTIONSLISTRS);

    PROCEDURE GETLIMITSLIST (
            V_REQUEST    IN OUT NOCOPY LIMITSLISTRQ,
            V_RESPONSE   IN OUT NOCOPY LIMITSLISTRS);

    PROCEDURE GETCHANNELSLIST (
            V_REQUEST    IN OUT NOCOPY CHANNELSLISTRQ,
            V_RESPONSE   IN OUT NOCOPY CHANNELSLISTRS);

    PROCEDURE SETSTATUS (
            V_REQUEST    IN OUT NOCOPY SETSTATUSRQ,
            V_RESPONSE   IN OUT NOCOPY SETSTATUSRS);

    PROCEDURE SETLIMIT (
            V_REQUEST    IN OUT NOCOPY SETLIMITRQ,
            V_RESPONSE   IN OUT NOCOPY SETLIMITRS);

    PROCEDURE SETCHANNEL (
            V_REQUEST    IN OUT NOCOPY SETCHANNELRQ,
            V_RESPONSE   IN OUT NOCOPY SETCHANNELRS);
    PROCEDURE GETBALANCE (
            V_REQUEST    IN OUT NOCOPY BALANCERQ,
            V_RESPONSE   IN OUT NOCOPY BALANCERS);

    PROCEDURE GETPRODUCTSLIST (
            V_REQUEST    IN OUT NOCOPY PRODUCTSLISTRQ,
            V_RESPONSE   IN OUT NOCOPY PRODUCTSLISTRS);

    PROCEDURE PINGAPI (
        V_REQUEST    IN OUT NOCOPY PINGSRVRQ,
        V_RESPONSE   IN OUT NOCOPY PINGSRVRS);

    PROCEDURE SETCOUNTRY (
        V_REQUEST    IN OUT NOCOPY SETCOUNTRYRQ,
        V_RESPONSE   IN OUT NOCOPY SETCOUNTRYRS);

    PROCEDURE GETCOUNTRYSLIST (
        V_REQUEST    IN OUT NOCOPY COUNTRYSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY COUNTRYSLISTRS);

    PROCEDURE GETCOUNTRIESLIST (
        V_REQUEST    IN OUT NOCOPY COUNTRIESLISTRQ,
        V_RESPONSE   IN OUT NOCOPY COUNTRIESLISTRS);

    PROCEDURE GETREASONSLIST (
        V_REQUEST    IN OUT NOCOPY REASONSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY REASONSLISTRS);

    PROCEDURE GETCHECKSIZESLIST (
        V_REQUEST    IN OUT NOCOPY CHECKSIZESLISTRQ,
        V_RESPONSE   IN OUT NOCOPY CHECKSIZESLISTRS);

    PROCEDURE GETLOCATIONSLIST (
        V_REQUEST    IN OUT NOCOPY LOCATIONSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY LOCATIONSLISTRS);

    PROCEDURE GETSTATISTICS (
        V_REQUEST    IN OUT NOCOPY STATISTICSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY STATISTICSRS);

    PROCEDURE CREATECARD (
        V_REQUEST    IN OUT NOCOPY CREATECARDRQ,
        V_RESPONSE   IN OUT NOCOPY CREATECARDRS);

    PROCEDURE SECONDCARD (
        V_REQUEST    IN OUT NOCOPY SECONDCARDRQ,
        V_RESPONSE   IN OUT NOCOPY SECONDCARDRS);

    PROCEDURE REPLACECARD (
        V_REQUEST    IN OUT NOCOPY REPLACECARDRQ,
        V_RESPONSE   IN OUT NOCOPY REPLACECARDRS);

    PROCEDURE GETMINISTAT (
        V_REQUEST    IN OUT NOCOPY MINISTATRQ,
        V_RESPONSE   IN OUT NOCOPY MINISTATRS);

    PROCEDURE REQPIN (
        V_REQUEST    IN OUT NOCOPY REQPINRQ,
        V_RESPONSE   IN OUT NOCOPY REQPINRS);

    PROCEDURE REQCHECKBOOK (
        V_REQUEST    IN OUT NOCOPY CHECKBOOKRQ,
        V_RESPONSE   IN OUT NOCOPY CHECKBOOKRS);

    PROCEDURE REQRENEW (
        V_REQUEST    IN OUT NOCOPY REQRENEWRQ,
        V_RESPONSE   IN OUT NOCOPY REQRENEWRS);

    PROCEDURE SETTRANSFER (
        V_REQUEST    IN OUT NOCOPY TRANSFERRQ,
        V_RESPONSE   IN OUT NOCOPY TRANSFERRS);

    PROCEDURE ENROLL (
        V_REQUEST    IN OUT NOCOPY ENROLLRQ,
        V_RESPONSE   IN OUT NOCOPY ENROLLRS);

    PROCEDURE GETCARDINFO (
        V_REQUEST    IN OUT NOCOPY CARDINFORQ,
        V_RESPONSE   IN OUT NOCOPY CARDINFORS);

    PROCEDURE CREATEDEBIT (
        V_REQUEST    IN OUT NOCOPY CREATEDEBITRQ,
        V_RESPONSE   IN OUT NOCOPY CREATEDEBITRS);
END MB_INTERFACE_PKG;
/

-- Grants for Package
GRANT EXECUTE ON api_sif_mobile.mb_interface_pkg TO public
/


-- End of DDL Script for Package API_SIF_MOBILE.MB_INTERFACE_PKG

-- Start of DDL Script for Package API_SIF_MOBILE.MB_INTERFACE_TOOLS_PKG
-- Generated 18-Feb-21 08:50:49 from API_SIF_MOBILE@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.18.1.199)(PORT = 1528)))(CONNECT_DATA =(SERVICE_NAME = afb12c)))

CREATE OR REPLACE 
PACKAGE api_sif_mobile.mb_interface_tools_pkg
IS
    OK                              CONSTANT NUMBER := 0;
    NOK                             CONSTANT NUMBER := -1;
    ERROR                           CONSTANT NUMBER := -2;
    CUSTOMER_NOT_EXIST              CONSTANT NUMBER := 1;
    CUSTOMER_ENROLLED               CONSTANT NUMBER := 2;
    CUSTOMER_EXIST_NOT_ENROLLED     CONSTANT NUMBER := 3;
    CUSTOMER_NOT_ACTIVE             CONSTANT NUMBER := 4;
    CARD_NOT_EXIST                  CONSTANT NUMBER := 5;
    CARD_CORRECT                    CONSTANT NUMBER := 6;
    CARD_NOT_CORRECT                CONSTANT NUMBER := 7;
    CARD_NOT_ACTIVE                 CONSTANT NUMBER := 8;
    ACCOUNT_NOT_EXIST               CONSTANT NUMBER := 9;
    ACCOUNT_CORRECT                 CONSTANT NUMBER := 10;
    ACCOUNT_NOT_CORRECT             CONSTANT NUMBER := 11;
    ACCOUNT_NOT_MAD                 CONSTANT NUMBER := 12;
    ACCOUNT_NOT_ACTIVE              CONSTANT NUMBER := 13;
    BANK_NOT_EXIST                  CONSTANT NUMBER := 14;

    PROCEDURE TRACE_MB_EXCHANGE (
        P_PACKAGE_NAME         PROCESSING_TRACES.PACKAGE_NAME%TYPE,
        P_PROCEDURE_NAME       PROCESSING_TRACES.PROCEDURE_NAME%TYPE,
        P_TRACE_LINE           PROCESSING_TRACES.TRACE_LINE%TYPE,
        P_TRACE_DESCRIPTION    PROCESSING_TRACES.TRACE_DESCRIPTION%TYPE);

    PROCEDURE LOG_MB_EXCHANGE (P_PROCEDURE_NAME    VARCHAR2,
                                P_AUT_CODE    AUTHORIZATION.AUT_CODE%TYPE,
                                P_REQUEST_ID    VARCHAR2,
                                P_REQUEST           XMLTYPE,
                                P_RESPONSE          XMLTYPE);
    FUNCTION CHECKCUSTOMER (
        P_CUS_IDEN   IN     CUSTOMER_CARDHOLDER.CUS_IDEN%TYPE,
        P_CUS_CODE   OUT    CUSTOMER_CARDHOLDER.CUS_CODE%TYPE,
        P_STATUS  IN OUT NOCOPY STATUSSTRUCT)RETURN NUMBER;

    FUNCTION CHECKACCOUNT (
        P_ACC_NUMB   IN     ACCOUNT.ACC_NUMB%TYPE,
        P_ACC_CUS_CODE   IN    ACCOUNT.ACC_CUS_CODE%TYPE,
        P_STATUS  IN OUT NOCOPY STATUSSTRUCT)
        RETURN NUMBER;

    FUNCTION CHECKCARD (
        P_CAR_CODE   IN     CARD.CAR_CODE%TYPE,
        P_CAR_CUS_CODE   IN    CARD.CAR_CUS_CODE%TYPE,
        P_STATUS  IN OUT NOCOPY STATUSSTRUCT)RETURN NUMBER;

    FUNCTION WALLETREGISTRATIONCONTROL (
        V_REQUEST    IN OUT NOCOPY REGISTRATIONRQ,
        V_RESPONSE   IN OUT NOCOPY REGISTRATIONRS) RETURN NUMBER;

    FUNCTION PROCESSCARDSLIST (
        V_REQUEST    IN OUT NOCOPY CARDSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY CARDSLISTRS)
        RETURN NUMBER;

    FUNCTION PROCESSTRANSACTIONSLIST (
        V_REQUEST    IN OUT NOCOPY TRANSACTIONSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY TRANSACTIONSLISTRS)
        RETURN NUMBER;

    FUNCTION PROCESSLIMITSLIST (
        V_REQUEST    IN OUT NOCOPY LIMITSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY LIMITSLISTRS)
        RETURN NUMBER;

    FUNCTION PROCESSCHANNELSLIST (
        V_REQUEST    IN OUT NOCOPY CHANNELSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY CHANNELSLISTRS)
        RETURN NUMBER;

    FUNCTION PROCESSSTATUSCHANGE (
        V_REQUEST    IN OUT NOCOPY SETSTATUSRQ,
        V_RESPONSE   IN OUT NOCOPY SETSTATUSRS)
        RETURN NUMBER;

    FUNCTION ACTIVATION(
        V_REQUEST    IN OUT NOCOPY SETSTATUSRQ,
        V_RESPONSE   IN OUT NOCOPY SETSTATUSRS)
        RETURN NUMBER;

    FUNCTION OPPOSITION(
        V_REQUEST    IN OUT NOCOPY SETSTATUSRQ,
        V_RESPONSE   IN OUT NOCOPY SETSTATUSRS)
        RETURN NUMBER;

    FUNCTION MOTO(
        V_REQUEST    IN OUT NOCOPY SETSTATUSRQ,
        V_RESPONSE   IN OUT NOCOPY SETSTATUSRS)
        RETURN NUMBER;

    FUNCTION PAYMENT(
        V_REQUEST    IN OUT NOCOPY SETSTATUSRQ,
        V_RESPONSE   IN OUT NOCOPY SETSTATUSRS)
        RETURN NUMBER;

    FUNCTION PROCESSLIMITCHANGE (
        V_REQUEST    IN OUT NOCOPY SETLIMITRQ,
        V_RESPONSE   IN OUT NOCOPY SETLIMITRS)
        RETURN NUMBER;

    FUNCTION PROCESSCHANNELCHANGE (
        V_REQUEST    IN OUT NOCOPY SETCHANNELRQ,
        V_RESPONSE   IN OUT NOCOPY SETCHANNELRS)
        RETURN NUMBER;

    FUNCTION PROCESSBALANCE (
        V_REQUEST    IN OUT NOCOPY BALANCERQ,
        V_RESPONSE   IN OUT NOCOPY BALANCERS)
        RETURN NUMBER;

    FUNCTION PROCESSCREATECARD (V_REQUEST    IN OUT NOCOPY CREATECARDRQ,
                                V_RESPONSE   IN OUT NOCOPY CREATECARDRS)
        RETURN NUMBER;

    FUNCTION PROCESSPRODUCTSLIST (
        V_REQUEST    IN OUT NOCOPY PRODUCTSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY PRODUCTSLISTRS)
        RETURN NUMBER;

    FUNCTION PROCESSACCOUNTSLIST (
        V_REQUEST    IN OUT NOCOPY ACCOUNTSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY ACCOUNTSLISTRS)
        RETURN NUMBER;

   FUNCTION PROCESSRESTCOUNTRYSLIST (
        V_REQUEST    IN OUT NOCOPY COUNTRYSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY COUNTRYSLISTRS)
        RETURN NUMBER;

    FUNCTION PROCESSCOUNTRYCHANGE (
        V_REQUEST    IN OUT NOCOPY SETCOUNTRYRQ,
        V_RESPONSE   IN OUT NOCOPY SETCOUNTRYRS)
        RETURN NUMBER;

    FUNCTION CHECKBANK (
        P_BAN_CODE   IN     BANK.BAN_CODE%TYPE,
        P_STATUS  IN OUT NOCOPY STATUSSTRUCT)
        RETURN NUMBER;

    FUNCTION PROCESSCOUNTRIESLIST (
        V_REQUEST    IN OUT NOCOPY COUNTRIESLISTRQ,
        V_RESPONSE   IN OUT NOCOPY COUNTRIESLISTRS)
        RETURN NUMBER;

    FUNCTION PROCESSREASONSLIST (
        V_REQUEST    IN OUT NOCOPY REASONSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY REASONSLISTRS)
        RETURN NUMBER;

    FUNCTION PROCESSCHECKSIZESLIST (
        V_REQUEST    IN OUT NOCOPY CHECKSIZESLISTRQ,
        V_RESPONSE   IN OUT NOCOPY CHECKSIZESLISTRS)
        RETURN NUMBER;

    FUNCTION PROCESSLOCATIONSLIST (
        V_REQUEST    IN OUT NOCOPY LOCATIONSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY LOCATIONSLISTRS)
        RETURN NUMBER;

    FUNCTION PROCESSSTATISTICS (
        V_REQUEST    IN OUT NOCOPY STATISTICSLISTRQ,
        V_RESPONSE   IN OUT NOCOPY STATISTICSRS)
        RETURN NUMBER;

    FUNCTION PROCESSSECONDCARD (V_REQUEST    IN OUT NOCOPY SECONDCARDRQ,
                                V_RESPONSE   IN OUT NOCOPY SECONDCARDRS)
        RETURN NUMBER;


    FUNCTION PROCESSREPLACECARD (V_REQUEST    IN OUT NOCOPY REPLACECARDRQ,
                                V_RESPONSE   IN OUT NOCOPY REPLACECARDRS)
        RETURN NUMBER;

    FUNCTION PROCESSMINISTAT (
        V_REQUEST    IN OUT NOCOPY MINISTATRQ,
        V_RESPONSE   IN OUT NOCOPY MINISTATRS)
        RETURN NUMBER;

    FUNCTION PROCESSREQRENEW (V_REQUEST    IN OUT NOCOPY REQRENEWRQ,
                                V_RESPONSE   IN OUT NOCOPY REQRENEWRS)
        RETURN NUMBER;

    FUNCTION PROCESSREQPIN (V_REQUEST    IN OUT NOCOPY REQPINRQ,
                                V_RESPONSE   IN OUT NOCOPY REQPINRS)
        RETURN NUMBER;

    FUNCTION PROCESSREQCHECKBOOK (V_REQUEST    IN OUT NOCOPY CHECKBOOKRQ,
                                V_RESPONSE   IN OUT NOCOPY CHECKBOOKRS)
        RETURN NUMBER;

   FUNCTION PROCESSTRANSFER (V_REQUEST    IN OUT NOCOPY TRANSFERRQ,
                                V_RESPONSE   IN OUT NOCOPY TRANSFERRS)
        RETURN NUMBER;

   FUNCTION PROCESSENROLLMENT (
        V_REQUEST    IN OUT NOCOPY ENROLLRQ,
        V_RESPONSE   IN OUT NOCOPY ENROLLRS)
        RETURN NUMBER;

   FUNCTION WALLETGETREGISTRATION (
        V_REQUEST    IN OUT NOCOPY REGISTRATIONRQ,
        V_RESPONSE   IN OUT NOCOPY REGISTRATIONRS)
        RETURN NUMBER;

    FUNCTION PROCESSCARDINFO (
        V_REQUEST    IN OUT NOCOPY CARDINFORQ,
        V_RESPONSE   IN OUT NOCOPY CARDINFORS)
        RETURN NUMBER;

    FUNCTION PROCESSCREATEDEBIT (
        V_REQUEST    IN OUT NOCOPY CREATEDEBITRQ,
        V_RESPONSE   IN OUT NOCOPY CREATEDEBITRS)
        RETURN NUMBER;

   END MB_INTERFACE_TOOLS_PKG;
/

-- Grants for Package
GRANT EXECUTE ON api_sif_mobile.mb_interface_tools_pkg TO public
/


-- End of DDL Script for Package API_SIF_MOBILE.MB_INTERFACE_TOOLS_PKG

-- Start of DDL Script for Package API_SIF_MOBILE.MB_RESP_PKG
-- Generated 18-Feb-21 08:50:55 from API_SIF_MOBILE@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.18.1.199)(PORT = 1528)))(CONNECT_DATA =(SERVICE_NAME = afb12c)))

CREATE OR REPLACE 
PACKAGE api_sif_mobile.mb_resp_pkg IS


    MB_SUCCESS_C CONSTANT  CHAR(5):='00000';
    MB_SUCCESS_D CONSTANT  CHAR(1):='';
    MB_ERROR_C   CONSTANT  CHAR(5):='80000';
    MB_SQL_C     CONSTANT  CHAR(5):='80001';
    MB_TRACE_C   CONSTANT  CHAR(5):='80002';

    WT_90000_C CONSTANT  CHAR(5):='90000';
    WT_90000_D CONSTANT  CHAR(18):='Client introuvable';
    MB_90001_C CONSTANT  CHAR(5):='90001';
    MB_90001_D CONSTANT  CHAR(27):='Statut de la carte invalide';
    MB_90002_C CONSTANT  CHAR(5):='90002';
    MB_90002_D CONSTANT  CHAR(33):='Erreur generation numéro de carte';
    MB_90003_C CONSTANT  CHAR(5):='90003';
    MB_90003_D CONSTANT  CHAR(35):='Erreur récupération plafond produit';
    MB_90004_C CONSTANT  CHAR(5):='90004';
    MB_90004_D CONSTANT  CHAR(29):='Donnée de plafond introuvable';
    MB_90005_C CONSTANT  CHAR(5):='90005';
    MB_90005_D CONSTANT  CHAR(22):='Client déjà inscrit';
    MB_90006_C CONSTANT  CHAR(5):='90006';
    MB_90006_D CONSTANT  CHAR(18):='Compte introuvable';
    MB_90007_C CONSTANT  CHAR(5):='90007';
    MB_90007_D CONSTANT  CHAR(16):='Carte incorrecte';
    MB_90008_C CONSTANT  CHAR(5):='90008';
    MB_90008_D CONSTANT  CHAR(38):='Cumul max dépasse cumul max du produit';
    MB_90009_C CONSTANT  CHAR(5):='90009';
    MB_90009_D CONSTANT  CHAR(16):='Compte incorrect';
    MB_90010_C CONSTANT  CHAR(5):='90010';
    MB_90010_D CONSTANT  CHAR(17):='Carte introuvable';
    MB_90011_C CONSTANT  CHAR(5):='90011';
    MB_90011_D CONSTANT  CHAR(40):='Compte avec une devise différente de DHS';
    MB_90012_C CONSTANT  CHAR(5):='90012';
    MB_90012_D CONSTANT  CHAR(32):='problème de génération de compte';
    MB_90013_C CONSTANT  CHAR(5):='90013';
    MB_90013_D CONSTANT  CHAR(21):='Client non enregistré';
    MB_90014_C CONSTANT  CHAR(5):='90014';
    MB_90014_D CONSTANT  CHAR(22):='Code ville introuvable';
    MB_90015_C CONSTANT  CHAR(5):='90015';
    MB_90015_D CONSTANT  CHAR(29):='Data base sever not available';
    MB_90016_C CONSTANT  CHAR(5):='90016';
    MB_90016_D CONSTANT  CHAR(34):='Erreur de vérification des données';
    MB_90017_C CONSTANT  CHAR(5):='90017';
    MB_90017_D CONSTANT  CHAR(18):='Agence introuvable';
    MB_90018_C CONSTANT  CHAR(5):='90018';
    MB_90018_D CONSTANT  CHAR(21):='Catégorie introuvable';
    MB_90019_C CONSTANT  CHAR(5):='90019';
    MB_90019_D CONSTANT  CHAR(47):='Erreur lors du vérification du status du client';
    MB_90020_C CONSTANT  CHAR(5):='90020';
    MB_90020_D CONSTANT  CHAR(48):='Les données de l enregistrement sont incorrectes';
    MB_90021_C CONSTANT  CHAR(5):='90021';
    MB_90021_D CONSTANT  CHAR(24):='Donnée canal introuvable';
    MB_90022_C CONSTANT  CHAR(5):='90022';
    MB_90022_D CONSTANT  CHAR(23):='Donnée pays introuvable';
    MB_90023_C CONSTANT  CHAR(5):='90023';
    MB_90023_D CONSTANT  CHAR(18):='Banque introuvable';
    MB_90024_C CONSTANT  CHAR(5):='90024';
    MB_90024_D CONSTANT  CHAR(19):='Produit introuvable';
    MB_90025_C CONSTANT  CHAR(5):='90025';
    MB_90025_D CONSTANT  CHAR(34):='Type de produit non pris en charge';
    MB_90026_C CONSTANT  CHAR(5):='90026';
    MB_90026_D CONSTANT  CHAR(27):='Statut de compte non valide';
    MB_90027_C CONSTANT  CHAR(5):='90027';
    MB_90027_D CONSTANT  CHAR(74):='Le compte par défaut de ce client a déjà un lien avec une carte principale';
    MB_90028_C CONSTANT  CHAR(5):='90028';
    MB_90028_D CONSTANT  CHAR(35):='Type de la carte non pris en charge';
    MB_90029_C CONSTANT  CHAR(5):='90029';
    MB_90029_D CONSTANT  CHAR(33):='Raison de remplacement incorrecte';
    MB_90030_C CONSTANT  CHAR(5):='90030';
    MB_90030_D CONSTANT  CHAR(14):='Client inactif';
    MB_90031_C CONSTANT  CHAR(5):='90031';
    MB_90031_D CONSTANT  CHAR(14):='Carte Inactive';
    MB_90032_C CONSTANT  CHAR(5):='90032';
    MB_90032_D CONSTANT  CHAR(14):='Compte inactif';
    MB_90033_C CONSTANT  CHAR(5):='90033';
    MB_90033_D CONSTANT  CHAR(33):='GET SCREEN SERVER INTERFCAE ERROR';
    MB_90034_C CONSTANT  CHAR(5):='90034';
    MB_90034_D CONSTANT  CHAR(23):='GET_INTERNAL_STAN ERROR';
    MB_90035_C CONSTANT  CHAR(5):='90035';
    MB_90035_D CONSTANT  CHAR(25):='REQ AUTHORIZATION ERROR: ';
    MB_90036_C CONSTANT  CHAR(5):='90036';
    MB_90036_D CONSTANT  CHAR(38):='Demande de remplacement est déjà faite';
    MB_90037_C CONSTANT  CHAR(5):='90037';
    MB_90037_D CONSTANT  CHAR(20):='Demande déjà envoyée';
    MB_90038_C CONSTANT  CHAR(5):='90038';
    MB_90038_D CONSTANT  CHAR(29):='Taille du chéquier incorrecte';
    MB_90039_C CONSTANT  CHAR(5):='90039';
    MB_90039_D CONSTANT  CHAR(44):='Le renouvellement automatique est déjà actif';
END MB_RESP_PKG;
/

-- Grants for Package
GRANT EXECUTE ON api_sif_mobile.mb_resp_pkg TO public
/


-- End of DDL Script for Package API_SIF_MOBILE.MB_RESP_PKG

-- Start of DDL Script for Package API_SIF_MOBILE.MB_XML_TOOLS
-- Generated 18-Feb-21 08:50:55 from API_SIF_MOBILE@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.18.1.199)(PORT = 1528)))(CONNECT_DATA =(SERVICE_NAME = afb12c)))

CREATE OR REPLACE 
package                        api_sif_mobile.mb_xml_tools is
 -- Public function and procedure declarations
  function xml2json(i_xml in xmltype) return xmltype;
  function xmltype2clob(i_xml in xmltype) return clob;
  function sql2xml(i_sql_string in varchar2) return xmltype;

end MB_XML_TOOLS;
/

-- Grants for Package
GRANT EXECUTE ON api_sif_mobile.mb_xml_tools TO public
/


-- End of DDL Script for Package API_SIF_MOBILE.MB_XML_TOOLS

