-- Start of DDL Script for Sequence API_SIF_MOBILE.X38_NUMBER
-- Generated 14-Feb-21 19:43:59 from API_SIF_MOBILE@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.18.1.199)(PORT = 1528)))(CONNECT_DATA =(SERVICE_NAME = afb12c)))

CREATE SEQUENCE api_sif_mobile.x38_number
  INCREMENT BY 1
  START WITH 1000000
  MINVALUE 123456
  MAXVALUE 999999
  NOCYCLE
  NOORDER
  CACHE 123456
/

-- Grants for Sequence
GRANT SELECT ON api_sif_mobile.x38_number TO public
/

-- End of DDL Script for Sequence API_SIF_MOBILE.X38_NUMBER

-- Start of DDL Script for Sequence API_SIF_MOBILE.XCHANNEL
-- Generated 14-Feb-21 19:43:59 from API_SIF_MOBILE@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.18.1.199)(PORT = 1528)))(CONNECT_DATA =(SERVICE_NAME = afb12c)))

CREATE SEQUENCE api_sif_mobile.xchannel
  INCREMENT BY 1
  START WITH 21
  MINVALUE 1
  MAXVALUE 9999999999
  NOCYCLE
  NOORDER
  CACHE 20
/

-- Grants for Sequence
GRANT SELECT ON api_sif_mobile.xchannel TO public
/

-- End of DDL Script for Sequence API_SIF_MOBILE.XCHANNEL

-- Start of DDL Script for Sequence API_SIF_MOBILE.XLOCATIONS_ENTITIES
-- Generated 14-Feb-21 19:44:00 from API_SIF_MOBILE@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.18.1.199)(PORT = 1528)))(CONNECT_DATA =(SERVICE_NAME = afb12c)))

CREATE SEQUENCE api_sif_mobile.xlocations_entities
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 99999999999999
  NOCYCLE
  NOORDER
  CACHE 20
/

-- Grants for Sequence
GRANT SELECT ON api_sif_mobile.xlocations_entities TO public
/

-- End of DDL Script for Sequence API_SIF_MOBILE.XLOCATIONS_ENTITIES

-- Start of DDL Script for Sequence API_SIF_MOBILE.XPHONE_NUMBER
-- Generated 14-Feb-21 19:44:00 from API_SIF_MOBILE@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.18.1.199)(PORT = 1528)))(CONNECT_DATA =(SERVICE_NAME = afb12c)))

CREATE SEQUENCE api_sif_mobile.xphone_number
  INCREMENT BY 1
  START WITH 2001111
  MINVALUE 222345
  MAXVALUE 9999999999999
  NOCYCLE
  NOORDER
  CACHE 222345
/

-- Grants for Sequence
GRANT SELECT ON api_sif_mobile.xphone_number TO public
/

-- End of DDL Script for Sequence API_SIF_MOBILE.XPHONE_NUMBER

